Just tidying up all of the of-scripts
of-keycheck is now integrated into of-identifier.

diff --git a/overlay-ubuntu-bionic/usr/local/sbin/of-timezone b/overlay-ubuntu-bionic/usr/local/sbin/of-timezone
--- a/overlay-ubuntu-bionic/usr/local/sbin/of-timezone
+++ b/overlay-ubuntu-bionic/usr/local/sbin/of-timezone
@@ -1,7 +1,22 @@
 #!/usr/bin/env bash
 
-# of-timezone v1.08 (29th April 2020) by Andrew Davison
-#  Checks or sets the timezone, returning the timezone once complete, with automatic update option.
+## of-timezone v1.09 (6th May 2020) by Andrew Davison
+##  Checks or sets the timezone, returning the timezone once complete, with automatic update option.
+
+
+usage() {
+	echo "Usage: $0 [action] [options]"
+	echo
+	echo "  check              :  Prints the current time zone to stdout."
+	echo "  set <timezone>     :  Sets the system time zone to given value."
+	echo "  update [platform]  :  Sets the system time zone automatically."
+	echo
+	exit 1
+}
+
+if [[ "$#" -gt 2 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
+	usage
+fi
 
 
 ## Change this to use an alternative time zone server.
@@ -12,17 +27,37 @@ SERVICE="/tz/lookup.php"
 
 THISSCRIPTPATH="$(cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"
 
-if [[ "$1" == "check" ]]; then
+if [[ "$1" == "check" ]] || [[ "$#" -eq 0 ]]; then
 
 	timedatectl status | grep "Time zone" | awk -F\  {'print $3'}
 	exit 0
 
 elif [[ "$1" == "set" ]]; then
 
-	/usr/bin/timedatectl set-timezone "$2"
-	RESULT=$(timedatectl status | grep "Time zone" | awk -F\  {'print $3'})
-	echo $RESULT
-	[[ "$RESULT" == "$1" ]] && exit 0 || exit 1
+	if [[ "$2" != "" ]]; then
+
+		/usr/bin/timedatectl set-timezone "$2"
+
+		RESULT=$(timedatectl status | grep "Time zone" | awk -F\  {'print $3'})
+
+		if [[ "$RESULT" == "$1" ]]; then
+
+			echo $RESULT
+			exit 0
+
+		else
+
+			echo "Failed to set the given time zone."
+			exit 1
+
+		fi
+
+	else
+
+		echo "No time zone provided."
+		exit 1
+
+	fi
 
 elif [[ "$1" == "update" ]]; then
 
@@ -45,8 +80,18 @@ elif [[ "$1" == "update" ]]; then
 
 		/usr/bin/timedatectl set-timezone "$TIMEZONE"
 		RESULT=$(timedatectl status | grep "Time zone" | awk -F\  {'print $3'})
-		echo $RESULT
-		[[ "$RESULT" == "$TIMEZONE" ]] && exit 0 || exit 1
+
+		if [[ "$RESULT" == "$1" ]]; then
+
+			echo $RESULT
+			exit 0
+
+		else
+
+			echo "Failed to set the given time zone."
+			exit 1
+
+		fi
 
 	else
 
@@ -54,10 +99,6 @@ elif [[ "$1" == "update" ]]; then
 		exit 1
 
 	fi
-
-else
-
-	echo "Usage: $0 <check> | <set> <timezone> | <update> [platform]"
 
 fi
 
