Update of-timezone

diff --git a/overlay-ubuntu-bionic/usr/local/sbin/of-timezone b/overlay-ubuntu-bionic/usr/local/sbin/of-timezone
--- a/overlay-ubuntu-bionic/usr/local/sbin/of-timezone
+++ b/overlay-ubuntu-bionic/usr/local/sbin/of-timezone
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# of-timezone v1.04 (29th April 2020) by Andrew Davison
+# of-timezone v1.06 (29th April 2020) by Andrew Davison
 #  Checks or sets the timezone, returning the timezone once complete, with automatic update option.
 
 
@@ -29,7 +29,7 @@ elif [[ "$1" == "update" ]]; then
 	[ -f /etc/lsb-release ] && source /etc/lsb-release
 
 	if [ -e /tmp/openframe.uid ] && [ -e /tmp/openframe.net ]; then
-		SYS_TYP="$(cat /tmp/openframe.uid)/$(cat /tmp/openframe.net)/$(echo ${DISTRIB_DESCRIPTION,,} | awk -F' ' '{print $1 "/" $2}')/${DISTRIB_CODENAME,,}/of-timezone"
+		SYS_TYP="$(cat /tmp/openframe.uid)/$(cat /tmp/openframe.net)/$(echo ${DISTRIB_DESCRIPTION,,} | awk -F' ' '{print $1 "/" $2}')/${DISTRIB_CODENAME,,}/$(uname -r)/of-timezone"
 	elif [ -f /etc/lsb-release ]; then
 		SYS_TYP="///$(hostname)/$(echo ${DISTRIB_DESCRIPTION,,} | awk -F' ' '{print $1 "/" $2}')/${DISTRIB_CODENAME,,}/$(uname -r)/of-timezone"
 	else
@@ -45,6 +45,11 @@ elif [[ "$1" == "update" ]]; then
 		RESULT=$(timedatectl status | grep "Time zone" | awk -F\  {'print $3'})
 		echo $RESULT
 		[[ "$RESULT" == "$TIMEZONE" ]] && exit 0 || exit 1
+
+	else
+
+		echo "Could not understand the server's response."
+		exit 1
 
 	fi
 
